# openapi
openapi:
	sh openapi-generator/openapi-generator.sh

# expo
expo-start-dev:
	npx expo start -c

expo-start-stag:
	NODE_ENV=stag npx expo start -c

expo-build-web:
	npx expo export --platform web
